max_seq_len: 2048
global_seed: 17

# Run Name
run_name: mcli-mpt1B_eng_20BT_v2 # If left blank, will be read from env var $RUN_NAME

# Model
model:
  name: mpt_causal_lm
  init_device: meta
  d_model: 2048
  n_heads: 16 # Modified 24->16 so that d_head == 128 to statisfy FlashAttention
  n_layers: 24
  expansion_ratio: 4
  max_seq_len: ${max_seq_len}
  vocab_size: 50368
  attn_config:
    attn_impl: triton

# Tokenizer
tokenizer:
  name: EleutherAI/gpt-neox-20b
  kwargs:
    model_max_length: ${max_seq_len}

# Dataloaders
train_loader:
  name: text
  dataset:
    shuffle: true
    max_seq_len: ${max_seq_len}
    shuffle_seed: ${global_seed}
    cache_limit: 900gb
    streams:
      cache_0___label__en:
        local: ./cache_stream/cache_0___label__en
        remote: s3://llm-spark/llm/pretrain_data/mds_data/snap_2023_23/sh_0/__label__en
        split: train
      cache_1___label__en:
        local: ./cache_stream/cache_1___label__en
        remote: s3://llm-spark/llm/pretrain_data/mds_data/snap_2023_23/sh_1/__label__en
        split: train
      cache_2___label__en:
        local: ./cache_stream/cache_2___label__en
        remote: s3://llm-spark/llm/pretrain_data/mds_data/snap_2023_23/sh_2/__label__en
        split: train
      cache_3___label__en:
        local: ./cache_stream/cache_3___label__en
        remote: s3://llm-spark/llm/pretrain_data/mds_data/snap_2023_23/sh_3/__label__en
        split: train
      cache_5___label__en:
        local: ./cache_stream/cache_5___label__en
        remote: s3://llm-spark/llm/pretrain_data/mds_data/snap_2023_23/sh_5/__label__en
        split: train
      cache_6___label__en:
        local: ./cache_stream/cache_6___label__en
        remote: s3://llm-spark/llm/pretrain_data/mds_data/snap_2023_23/sh_6/__label__en
        split: train
      cache_7___label__en:
        local: ./cache_stream/cache_7___label__en
        remote: s3://llm-spark/llm/pretrain_data/mds_data/snap_2023_23/sh_7/__label__en
        split: train
      cache_8___label__en:
        local: ./cache_stream/cache_8___label__en
        remote: s3://llm-spark/llm/pretrain_data/mds_data/snap_2023_23/sh_8/__label__en
        split: train
      cache_9___label__en:
        local: ./cache_stream/cache_9___label__en
        remote: s3://llm-spark/llm/pretrain_data/mds_data/snap_2023_23/sh_9/__label__en
        split: train
      cache_10___label__en:
        local: ./cache_stream/cache_10___label__en
        remote: s3://llm-spark/llm/pretrain_data/mds_data/snap_2023_23/sh_10/__label__en
        split: train
      cache_11___label__en:
        local: ./cache_stream/cache_11___label__en
        remote: s3://llm-spark/llm/pretrain_data/mds_data/snap_2023_23/sh_11/__label__en
        split: train
      cache_12___label__en:
        local: ./cache_stream/cache_12___label__en
        remote: s3://llm-spark/llm/pretrain_data/mds_data/snap_2023_23/sh_12/__label__en
        split: train
      cache_13___label__en:
        local: ./cache_stream/cache_13___label__en
        remote: s3://llm-spark/llm/pretrain_data/mds_data/snap_2023_23/sh_13/__label__en
        split: train
      cache_14___label__en:
        local: ./cache_stream/cache_14___label__en
        remote: s3://llm-spark/llm/pretrain_data/mds_data/snap_2023_23/sh_14/__label__en
        split: train
      cache_15___label__en:
        local: ./cache_stream/cache_15___label__en
        remote: s3://llm-spark/llm/pretrain_data/mds_data/snap_2023_23/sh_15/__label__en
        split: train
      cache_16___label__en:
        local: ./cache_stream/cache_16___label__en
        remote: s3://llm-spark/llm/pretrain_data/mds_data/snap_2023_23/sh_16/__label__en
        split: train
      cache_17___label__en:
        local: ./cache_stream/cache_17___label__en
        remote: s3://llm-spark/llm/pretrain_data/mds_data/snap_2023_23/sh_17/__label__en
        split: train
      cache_18___label__en:
        local: ./cache_stream/cache_18___label__en
        remote: s3://llm-spark/llm/pretrain_data/mds_data/snap_2023_23/sh_18/__label__en
        split: train
      cache_19___label__en:
        local: ./cache_stream/cache_19___label__en
        remote: s3://llm-spark/llm/pretrain_data/mds_data/snap_2023_23/sh_19/__label__en
        split: train
      cache_20___label__en:
        local: ./cache_stream/cache_20___label__en
        remote: s3://llm-spark/llm/pretrain_data/mds_data/snap_2023_23/sh_20/__label__en
        split: train
      cache_21___label__en:
        local: ./cache_stream/cache_21___label__en
        remote: s3://llm-spark/llm/pretrain_data/mds_data/snap_2023_23/sh_21/__label__en
        split: train
      cache_22___label__en:
        local: ./cache_stream/cache_22___label__en
        remote: s3://llm-spark/llm/pretrain_data/mds_data/snap_2023_23/sh_22/__label__en
        split: train
      cache_23___label__en:
        local: ./cache_stream/cache_23___label__en
        remote: s3://llm-spark/llm/pretrain_data/mds_data/snap_2023_23/sh_23/__label__en
        split: train
      cache_24___label__en:
        local: ./cache_stream/cache_24___label__en
        remote: s3://llm-spark/llm/pretrain_data/mds_data/snap_2023_23/sh_24/__label__en
        split: train
      cache_26___label__en:
        local: ./cache_stream/cache_26___label__en
        remote: s3://llm-spark/llm/pretrain_data/mds_data/snap_2023_23/sh_26/__label__en
        split: train
      cache_27___label__en:
        local: ./cache_stream/cache_27___label__en
        remote: s3://llm-spark/llm/pretrain_data/mds_data/snap_2023_23/sh_27/__label__en
        split: train
      cache_28___label__en:
        local: ./cache_stream/cache_28___label__en
        remote: s3://llm-spark/llm/pretrain_data/mds_data/snap_2023_23/sh_28/__label__en
        split: train
      cache_29___label__en:
        local: ./cache_stream/cache_29___label__en
        remote: s3://llm-spark/llm/pretrain_data/mds_data/snap_2023_23/sh_29/__label__en
        split: train
  drop_last: true
  num_workers: 8

# Optimization
scheduler:
  name: cosine_with_warmup
  t_warmup: 100ba
  alpha_f: 0.1

optimizer:
  name: decoupled_adamw
  lr: 2.0e-4
  betas:
  - 0.9
  - 0.95
  eps: 1.0e-08
  weight_decay: 0.0

algorithms:
  gradient_clipping:
    clipping_type: norm
    clipping_threshold: 1.0

max_duration: 1ep
eval_interval: 1
eval_first: false
eval_subset_num_batches: -1
global_train_batch_size: 1024

# System
seed: ${global_seed}
device_eval_batch_size: 4
device_train_microbatch_size: 4
# device_train_microbatch_size: auto
precision: amp_bf16

# FSDP
fsdp_config:
  sharding_strategy: FULL_SHARD # NO_SHARD, FULL_SHARD, SHARD_GRAD_OP
  mixed_precision: PURE
  activation_checkpointing: false
  activation_checkpointing_reentrant: false
  activation_cpu_offload: false
  limit_all_gathers: true
  verbose: false

# Logging
progress_bar: false
log_to_console: true
console_log_interval: 1ba

callbacks:
  speed_monitor:
    window_size: 10
  lr_monitor: {}
  memory_monitor: {}
  runtime_estimator: {}

loggers:
  wandb:
    rank_zero_only: 'False'
    init_kwargs:
      mode: online

# Checkpoint to local filesystem or remote object store
save_interval: 100ba
save_num_checkpoints_to_keep: 1  # Important, this cleans up checkpoints saved to DISK
save_folder: /raid/palash.kamble/LLM/checkpoints/mcli-mpt1B_eng_20BT_v2
# save_folder: s3://my-bucket/my-folder/{run_name}/checkpoints

# Load from local filesystem or remote object store
# load_path: ./gpt-1b/checkpoints/latest-rank{rank}.pt
# load_path: s3://my-bucket/my-folder/gpt-1b/checkpoints/latest-rank{rank}.pt
